"""amplifier_memory — the one home for memory behaviour (AGENTS.md rule 11).

Import this and you have the whole store: `init`, `save`, `edit`, `forget`,
`list_memories`, `log_usage`, `record_citation`, `why`, `store_home`, the reports
`status`, `review`,
`doctor` and `update_check`, and the exceptions a refusal raises. It depends on no
`amplifier_*` package and on no CLI framework — PyYAML, which reads the instance's
`config.yaml` (store.v3 §2), is its one third-party dependency — so the CLI, the memory tool,
the inject hook and the Phase 2 job are all thin adapters over the same code
(cli.v2 Core 9).

Every `amplifier-memory` verb is one of these functions plus printing:

| verb      | function                                        |
|-----------|-------------------------------------------------|
| `init`    | `init()`                                        |
| `status`  | `status()` -> `StatusReport.render()`           |
| `why`     | `why(id)` -> `format_why()`                     |
| `review`  | `review()`                                      |
| `doctor`  | `doctor()` -> `DoctorReport.render()`           |
| `doctor --repair` | `repair_store()` -> `RepairResult.render()` |
| `service` | `service_status(verb)`                          |
| `update`  | `run_update()` -> `UpdateReport.render()`       |
| `suggest` | `suggest_status()`                              |
"""

from .doctor import (
    SERVICE_VERBS,
    STALE_NOTE,
    SUBSTRATE_ROW,
    TIMER_ROW,
    DoctorReport,
    DoctorRow,
    doctor,
    installed_commit,
    remote_commit,
    service_status,
    substrate_row,
    suggest_status,
    timer_row,
    update_check,
    update_plan,
)
from .inbox import (
    DECLINED,
    EXPIRY_DAYS,
    INBOX,
    REVIEW_KEYS,
    REVIEW_PROMPT,
    Candidate,
    CorrectedAcceptanceInspectionRequired,
    CorrectedAcceptanceUnverified,
    Suggestion,
    UnknownSuggestion,
    accept,
    accept_corrected,
    append,
    decline,
    declined_entries,
    declined_line,
    declined_quotes,
    declined_texts,
    expire,
    is_declined,
    is_interactive,
    pending,
    render_pending,
    render_review_page,
    review_action,
    review_one,
    reviewing_session_id,
    skip,
)
from .instance import (
    HOME_FLAG,
    SEED_DEFAULT,
    SEED_QUESTION,
    InstanceReport,
    build_instance,
    default_instance,
    split_home,
)
from .service import (
    SERVICE_UNIT,
    TIMER_UNIT,
    InstalledTimer,
    ServiceResult,
    ServiceStatus,
    installed_timers,
    instance_tag,
    service_unit,
    timer_present,
    timer_unit,
)
from .service import (
    install as service_install,
)
from .service import (
    status as service_state,
)
from .service import (
    uninstall as service_uninstall,
)
from .status import (
    StatusReport,
    format_why,
    last_suggest_run,
    render_list_page,
    review,
    status,
)
from .store import (
    CapExceeded,
    DuplicateMemory,
    GitFailed,
    InstanceDisabled,
    MalformedLine,
    MemoryError,
    Page,
    PageOutOfRange,
    QuoteNotHuman,
    RepairResult,
    StoreBusy,
    StoreCheck,
    StoreMalformed,
    StoreMissing,
    UnknownId,
    WriteNotLanded,
    default_home,
    display_path,
    edit,
    forget,
    init,
    instance_enabled,
    legacy_home,
    legacy_store_present,
    list_memories,
    log_usage,
    origin_from_env,
    page_bounds,
    read_memory_text,
    record_citation,
    record_session,
    repair_store,
    save,
    session_origins,
    store_home,
    verify_store,
    why,
)
from .suggest import (
    PROMPT,
    PROMPT_PREFIX,
    RUN_ARGV,
    MalformedReply,
    SuggestReport,
    last_log_line,
    log_path,
    parse_log_line,
    run_suggest,
    select_sessions,
)
from .update import (
    APP_BUNDLE_URI,
    BUNDLE_ADD_ARGV,
    BUNDLE_REMOVE_ARGV,
    UPGRADE_CLI_ARGV,
    StepResult,
    UpdateReport,
    run_update,
)

__all__ = [  # noqa: RUF022 - contract order (store, then the report surface), not alphabetical
    "init",
    "save",
    "edit",
    "forget",
    "list_memories",
    "read_memory_text",
    "log_usage",
    "record_citation",
    "why",
    "store_home",
    "default_home",
    "legacy_home",
    "legacy_store_present",
    "instance_enabled",
    "record_session",
    "session_origins",
    "origin_from_env",
    "verify_store",
    "repair_store",
    "StoreCheck",
    "RepairResult",
    "MalformedLine",
    "status",
    "StatusReport",
    "review",
    "format_why",
    "doctor",
    "DoctorReport",
    "DoctorRow",
    "update_check",
    "update_plan",
    "run_update",
    "UpdateReport",
    "StepResult",
    "APP_BUNDLE_URI",
    "UPGRADE_CLI_ARGV",
    "BUNDLE_REMOVE_ARGV",
    "BUNDLE_ADD_ARGV",
    "installed_commit",
    "remote_commit",
    "service_status",
    "SERVICE_VERBS",
    "SERVICE_UNIT",
    "TIMER_UNIT",
    # cli.v3 §6 / §8, added by lane W: a timer belongs to an INSTANCE. The unit names are
    # derived from the instance's path, `installed_timers` is what `status` lists, and
    # `build_instance` is the `init` verb (the store primitive plus the move offer, the
    # one seeding question and this instance's timer).
    "instance_tag",
    "service_unit",
    "timer_unit",
    "timer_present",
    "installed_timers",
    "InstalledTimer",
    "build_instance",
    "default_instance",
    "InstanceReport",
    "SEED_QUESTION",
    "SEED_DEFAULT",
    "HOME_FLAG",
    "split_home",
    "TIMER_ROW",
    "SUBSTRATE_ROW",
    "timer_row",
    "substrate_row",
    "service_install",
    "service_uninstall",
    "service_state",
    "ServiceResult",
    "ServiceStatus",
    "suggest_status",
    "INBOX",
    "DECLINED",
    "EXPIRY_DAYS",
    "Suggestion",
    "Candidate",
    "UnknownSuggestion",
    "CorrectedAcceptanceUnverified",
    "CorrectedAcceptanceInspectionRequired",
    "pending",
    "append",
    "accept",
    "accept_corrected",
    "decline",
    "skip",
    "expire",
    "is_declined",
    "declined_entries",
    "declined_line",
    "declined_quotes",
    "declined_texts",
    "render_pending",
    "render_review_page",
    "render_list_page",
    "last_suggest_run",
    "page_bounds",
    "Page",
    "display_path",
    "review_one",
    "review_action",
    "reviewing_session_id",
    "is_interactive",
    "REVIEW_KEYS",
    "REVIEW_PROMPT",
    "run_suggest",
    "SuggestReport",
    "MalformedReply",
    "select_sessions",
    "last_log_line",
    "parse_log_line",
    "log_path",
    "PROMPT",
    "PROMPT_PREFIX",
    "RUN_ARGV",
    "STALE_NOTE",
    "MemoryError",
    "CapExceeded",
    "DuplicateMemory",
    "UnknownId",
    "QuoteNotHuman",
    "StoreMissing",
    "InstanceDisabled",
    "StoreBusy",
    "WriteNotLanded",
    "StoreMalformed",
    "GitFailed",
    "PageOutOfRange",
]
